# configurations of field
TEAM_IS_POSITIVE = True

FIELD_LENGTH_MM = 9000
FIELD_WIDTH_MM = 6000
DEFENCE_X_MM = 1000
DEFENCE_Y_MM = 2000

FIELD_X_MIN = -FIELD_LENGTH_MM / 2
FIELD_X_MAX = FIELD_LENGTH_MM / 2
FIELD_Y_MIN = -FIELD_WIDTH_MM / 2
FIELD_Y_MAX = FIELD_WIDTH_MM / 2

ROBOT_RADIUS_MM = 70.0
SAFE_MARGIN = 30.0  #mm
BALL_R =  21.5 #mm


GRID_SPACING_MM = 500
BOUNDARY_SAMPLE_SPACING_MM = 500


# Active Voronoi/map-planning defaults.
VORONOI_MIN_CLEARANCE_MM = ROBOT_RADIUS_MM + SAFE_MARGIN
VORONOI_BOUNDARY_INSET_MM = 100.0
VORONOI_DENSITY_PERCENT = 60.0
VORONOI_MAX_DENSITY_NODES = 140
VORONOI_RENDER_DENSITY_PERCENT = 10.0
VORONOI_RENDER_MAX_DENSITY_NODES = 80
VORONOI_GENERATOR_MAX_DENSITY_NODES = 240
VORONOI_OBSTACLE_COST_WEIGHT = 2.0
VORONOI_GENERATOR_OBSTACLE_COST_WEIGHT = 0.0
VORONOI_HORIZON_MS = 250
VORONOI_TARGET_DEAD_ZONE_MM = 150.0
VORONOI_CONNECTION_COUNT = 8
VORONOI_CONNECTION_RADIUS_MM = 2200.0
VORONOI_ENDPOINT_REACH_MM = 70.0
VORONOI_ESCAPE_MARGIN_MM = 120.0
VORONOI_MIN_ESCAPE_STEP_MM = 250.0


# Voronoi navigator behaviour.
VORONOI_CHASE_SPEED_SCALE = 0.80
VORONOI_PRECISION_SPEED_SCALE = 0.75
VORONOI_WAYPOINT_REACHED_MM = 180.0
VORONOI_TARGET_STOP_MM = 80.0
VORONOI_FIELD_TARGET_MARGIN_MM = 100.0
VORONOI_PRECISION_RAMP_DIST_MM = 260.0
VORONOI_CHASE_RAMP_DIST_MM = 450.0
VORONOI_MIN_SPEED = 0.06
VORONOI_PRECISION_MIN_SPEED = 0.03
VORONOI_SMOOTH_ALPHA = 0.35
VORONOI_POSSESSION_DIST_MM = 90.0
VORONOI_POSSESSION_ANGLE_RAD = 0.015
VORONOI_STEAL_FRONT_DIST_MM = 650.0
VORONOI_STEAL_FRONT_ANGLE_RAD = 0.35

