# configurations of field
TEAM_IS_POSITIVE = True

FIELD_LENGTH_MM = 9000
FIELD_WIDTH_MM = 6000
DEFENCE_X_MM = 1000
DEFENCE_Y_MM = 2000

FIELD_X_MIN = -FIELD_LENGTH_MM / 2
FIELD_X_MAX = FIELD_LENGTH_MM / 2
FIELD_Y_MIN = -FIELD_WIDTH_MM / 2
FIELD_Y_MAX = FIELD_WIDTH_MM / 2

ROBOT_RADIUS_MM = 90.0
SAFE_MARGIN = 30.0  #mm
BALL_R =  21.5 #mm


GRID_SPACING_MM = 500
BOUNDARY_SAMPLE_SPACING_MM = 500

